### PR TITLE
Add Data upload functionality so that users can upload a csv and that data can be parsed as sensor data.

### PR DESCRIPTION
**Pull request by Birdbh**
This is built heavily on flask_wtf and requires the use of forms. This also re-factors home so that data can be created.

### CODE REVIEW

**Review by Reebs296 — COMMENTED** [review]
image
Just want to make sure this change to home.html is intentional, or if you just made a typo?

**Comment by Birdbh** [comment]
> image Just want to make sure this change to home.html is intentional, or if you just made a typo?

Good Catch! Fixed it now

**Review by Reebs296 — APPROVED** [review]
Looks good to me, thanks!

**Review by JamesShadowfyre — APPROVED** [review]
All changes for this PR look good.

**Pull request merged**
