### PR TITLE
Issue#147: Update index.html to match Flask Tutorial Set-Up

### LINKED ISSUE #147: Update index.html to match Flask Tutorial Set-Up

### PR DESCRIPTION
**Pull request by Reebs296**
Fixes #147

### CODE REVIEW

**Comment by Birdbh** [comment]
The code includes fragments like:

<h1>{{ post['title'] }}</h1>
          <div class="about">by {{ post['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}</div>
          
and 

<a class="action" href="{{ url_for('blog.create') }}">New</a>

These are not a part of the current project as object "post" and URL blog.create are for the flask tutorials blog web_app and our project won't have blog functionality.

**Comment by Reebs296** [comment]
Please see the changes I have made, to better match the project concept.

**Comment by Birdbh** [comment]
Not to shoot down another change, but I have difficulty understanding where much of this is coming from, for example:

<a class="action" href="{{ url_for('datasetInput.create') }}">New</a>
there is no plan for there to be a datasetInput.create page

Or

<a class="action" href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>

There is still a line in this commit that deals with posts and a blog.update page which we don't have

The jinja syntax is also commented out and I don't understand how the page would display using the base template without the syntax there. Sorry that these are not constructive comments

**Review by JamesShadowfyre — CHANGES_REQUESTED** [review]
This index file is not really needed in the current scope of the program. 
Let's reject this for now and close PR, we can come back to a file like this at a later point in time.

**Pull request closed without merging**
