### PR TITLE
Added downloading per issue 38

### PR DESCRIPTION
**Pull request by JamesShadowfyre**
Added downloads for premium users. Adds a download button which downloads as a PNG
per issue #38

### CODE REVIEW

**Review by Reebs296 — COMMENTED** [review]
Do you have an example data set that I can pass through, which it will recognize? I've tried some random excel files and it does not recognize it.

**Comment by Reebs296** [comment]
image
There is currently an issue with the way that the Bar Charts are showing up. The colour used for the bars is almost identical to the background, so it is impossible to view the data accurately. All other chart types are working fine, but this is how bar charts are downloading: 
Data4_7_2024, 9_59_18 PM

**Comment by Reebs296** [comment]
Data4_7_2024, 9_57_59 PM
Data4_7_2024, 10_01_48 PM
These both look fine.

**Comment by Reebs296** [comment]
I only just noticed this issue, it is not directly related to the changes here. I will revise it in a separate formatting issue.

**Comment by Jcp149** [comment]
bar colour could be a problem w border width or with since bar and line have 2 different names for how to colour them itr could be difficult for chart,js

**Comment by Jcp149** [comment]
on my end im not getting alarms to show up (line or log) as well as the download button is only for premium users

**Comment by JamesShadowfyre** [comment]
> on my end im not getting alarms to show up (line or log) as well as the download button is only for premium users

Download for premium is intended behaviour. 
For alarms, are they appearing in the table?

**Review by Reebs296 — APPROVED** [review]
Issues have been resolved. Looks good, thanks!

**Review by Birdbh — APPROVED** [review]
This works for me, I think Jefferey may be having issues because he is on mac. This works for me, the output pdf is great
image

**Pull request merged**
