### PR TITLE
adds an alarmer class and test class for it

### PR DESCRIPTION
**Pull request by Jcp149**
alarmer class intakes the sensor attached to the alarm and the high and low thresholds. this class allows the user to take a single input for high and low thresholds and makes it a list of however large the list length is of the repeated threshold to make it easy to translate the thresholds to chart.js lines.

### CODE REVIEW

**Review by Birdbh — CHANGES_REQUESTED** [review]
There is already an alarm.py class. Having an alarm, alarmManager, and alarmer class obfuscates the code. Consider refactoring existing classes.

**Comment by JamesShadowfyre** [comment]
This can probably go in the alarm class

**Comment by Jcp149** [comment]
kk ill move to alarm, didnt want to add to what burke was trying to get working

**Comment by Birdbh** [comment]
Should this be closed now that James has finished implementing alarm?

**Comment by Jcp149** [comment]
no @Birdbh , just waiting approval

**Review by JamesShadowfyre — CHANGES_REQUESTED** [review]
I actually think whats left here isnt needed at this point with changes in implementations of alarms

**Pull request closed without merging**
