### PR TITLE
Add Upgrade System

### PR DESCRIPTION
**Pull request by JamesShadowfyre**
Adds the ability to upgrade to a premium user. Payment features added. New landing page when not logged in

### CODE REVIEW

**Review by Reebs296 — APPROVED** [review]
Thanks for adding those changes, looks good.

**Comment by Jcp149** [comment]
new pages look great, good job, but when i try to upgrade it gives an internal server error. also, the upgrade screen has 2 fields of "credit card number" could be good to change one of them to "3 digit security number" and the other two "12 digit credit card number" just to be clear, or just the first change could be good tbh

**Comment by Jcp149** [comment]
Also, there are now 2 files of UPLOADED_DATA, not sure if thats a mistake

**Review by Jcp149 — APPROVED** [review]
After deleting the sqlite file, and running the test suite a new one was made and allowed me to register and upgrade seamlessly! great work on this implementation all the pages look great, maybe just delete that one UPLOADED_DATA file if its not supposed to be there!

**Pull request merged**
