### PR TITLE
Brkykrclk/issue180

### LINKED ISSUE #180: Develop Alarm Management Class for Enhanced Alarm Handling
The development of a new Alarm Management class designed to streamline the handling and management of alarms within the system

### PR DESCRIPTION
**Pull request by brkykrclk**
Fixes #180 and #179

### CODE REVIEW

**Review by Birdbh — APPROVED** [review]
We still need another design pattern, you may want to refactor this in the future to be more of an observer relationship:
image
For example our publisher would be the AlarmManager and the alarms would subscribe to it.
Right now AlarmManager has many of the same methods, connect, add, remove, check as  the Observer design pattern would implement. Furthermore for things like, remove all alarms in the UI, if it was an observer situation this would be really easy as all arlims in self.alarms could be notified to be set to is_active = False.

You can find more info here: https://refactoring.guru/design-patterns/observer

but we need another design patter and this could be a good way to build on what you have done in another sprint

**Comment by Birdbh** [comment]
Also you should add a label and what project this is for you Rohit will ding you points

**Comment by brkykrclk** [comment]
alright working on it

**Review by Jcp149 — APPROVED** [review]
tests pass and the alarm classes look great, after its refactored with the design pattern it will be perfect. great work qt

**Pull request merged**
