### PR TITLE
Jcp149/issue114

### PR DESCRIPTION
**Pull request by Jcp149**
implemented issue #68 and consequently created issue #114

Db implementation is complete, but the tests are being problematic.

### CODE REVIEW

**Review by Birdbh — APPROVED** [review]
We talked about this in our meeting, bug will be fixed in the future, I will approve because another issue has been created for the resulting issue

**Review by Reebs296 — APPROVED** [review]
Looks good.

**Comment by JamesShadowfyre** [comment]
> We talked about this in our meeting, bug will be fixed in the future, I will approve because another issue has been created for the resulting issue
@Birdbh What issue?

**Comment by JamesShadowfyre** [comment]
#114 was resolved. Marking this all complete and merging

**Pull request merged**
