### PR TITLE
Adding Registration Feature

### PR DESCRIPTION
**Pull request by JamesShadowfyre**
Adding the registration page feature issue #85

### CODE REVIEW

**Comment by Birdbh** [comment]
@JamesShadowfyre There are no reviews, they must be added or else...

**Comment by Birdbh** [comment]
@JamesShadowfyre Also, I believe your test file is in the wrong folder, I think all tests should be in test, none in src

**Review by Birdbh — COMMENTED** [review]
@JamesShadowfyre Also, I dont understand your code but as long as it pases the tests, all g

**Review by Birdbh — APPROVED** [review]
Test are in correct location now, love it, no issues I see

**Review by Jcp149 — COMMENTED** [review]
should we change the name of the test file to test_name so we can keep it consistent?

**Review by Birdbh — CHANGES_REQUESTED** [review]
When I run your tests they fail:
ERROR collecting tests/test_register.py __________________________________________________ 
ImportError while importing test module 'C:\Users\birdl\Desktop\Year 4\Term 2\COSC 310\Workspace\Engicoders\tests\test_register.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\birdl\anaconda3\envs\course02502\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_register.py:9: in <module>
    import flaskr.register as register
src\flaskr\register.py:6: in <module>
    from db import get_db
E   ModuleNotFoundError: No module named 'db


And when I navigate to http://127.0.0.1:5000/auth/register where I belive your site should be for user testing I get a No Found response

**Review by Birdbh — APPROVED** [review]
Tests pass, I did some user testing and it passes as well, so approved. Next week can you do login?

**Comment by Birdbh** [comment]
> Yes, starting today

Even better

**Comment by JamesShadowfyre** [comment]
This PR closes issues #85 and #101

**Review by Jcp149 — APPROVED** [review]
looks good, tests pass here too, thanks for updating all of this!

**Pull request merged**
