### PR TITLE
Birdbh/issue135 -> Creation of Base.html document with correct Jinja notaton, including header, footer, title, links

### PR DESCRIPTION
**Pull request by Birdbh**
In the future highlightin the current page may be useful: https://python-web.teclado.com/section12/lectures/03_base_template_and_nav_bar/

This was done similary to how the flask tutorial does it

Although it is not best practice I also re-arranged the html files, there was a base.html file in the wrong spot before this that was removed as well as an html file that was an accidental commit called "testLayout"

The register html file does not have anything and the main home html is a placeholder

### CODE REVIEW

**Comment by Birdbh** [comment]
image

**Review by Jcp149 — APPROVED** [review]
loooks good, thanks for using the base one again

**Review by JamesShadowfyre — APPROVED** [review]
No apparent errors. Looks good when run in environment testing.

**Comment by Jcp149** [comment]
thanks for adding a ss of the page too!

**Pull request merged**
