### PR TITLE
Create PythonRequirements.bat per #124

### PR DESCRIPTION
**Pull request by JamesShadowfyre**
#124

### CODE REVIEW

**Comment by Birdbh** [comment]
This needs reviewers, Assignees, Labels, and a Project assigned to it

**Review by Birdbh — APPROVED** [review]
My libraries and Burks libraries are here

**Comment by Birdbh** [comment]
This pull request has been assigned to @Reebs296 , Prediction and Alarm are waiting this approval to then be approved

**Review by Reebs296 — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
