### PR TITLE
Add Log-in Functionality per issue 51

### PR DESCRIPTION
**Pull request by JamesShadowfyre**
This adds login and logout functionality per #51 
It also addresses issues #100 #102 and #104 
Please test from a user perspective:
- Registering
- Logging in
- logging out 
Further, check the code for any code smell.

### CODE REVIEW

**Review by brkykrclk — APPROVED** [review]
Perfect, I think I understand my mistake for home.py while checking these

**Review by Birdbh — COMMENTED** [review]
This is a chunky change, I would like to take some more time to review this. I won't have time until 2 to give this a good review. Is this a blocker for anything right now?

**Review by Birdbh — CHANGES_REQUESTED** [review]
This is great work, I have included my user testing with 1 requested change:
image
When registering but having the Repeat Password not match, the error message is "<html><body>
<span style="color: rgb(21, 194, 27);">[Field must be equal to password.]</span>





</body>
</html>"
This should be instead that "Passwords are not equal" or "Passwords should match"

image
Re-Registering an existing account leads to an error which is great!

image

Login Errors when incorrect login is provided is great!

You have also made form classes for both login and register, this is good code smell practice and @brkykrclk may want to implement this for home if he thinks it could make it easier to code.

**Comment by JamesShadowfyre** [comment]
@Birdbh I have adjusted that login message. Please take some time to review this again when you have a moment.

**Review by Birdbh — APPROVED** [review]
image
Thank you for making those changes, looks great!

**Pull request merged**
