### PR TITLE
Issue#157: Update register.html for Content

### LINKED ISSUE #157: Update register.html for Content

### PR DESCRIPTION
**Pull request by Reebs296**
Fixes #157

### CODE REVIEW

**Review by Jcp149 — APPROVED** [review]
looks great, follows format of the flask tut we did!

**Comment by Birdbh** [comment]
This code turns the jinja syntax into comments, the jinja syntax is necessary for the page to display. Refer to the current login page for how the jinja has to be written not as a comment to display. This page as it is now will not render correctly with the base template

**Review by brkykrclk — APPROVED** [review]
Looks good

**Comment by Reebs296** [comment]
@Birdbh can you elaborate? I'm not sure what you mean for the page to display? What other file is calling on it that requires those bracket parts? is it the style.css?

**Review by Birdbh — APPROVED** [review]
We discussed this pull request in depth during the meeting, and I am going to approve it. James may use the branch in the future for another PR.

**Comment by JamesShadowfyre** [comment]
Closing this PR. Conflicts with merged material. Will create an issue outlining redesign

**Pull request closed without merging**
