### PR TITLE
added fixed M2 to deliverables

### LINKED ISSUE #208: Fix M2
Go through the M2 document and apply all of the inputs that rohit left on it and add it to the deliverable folder. main issues are with the case diagram and some things need more explaining. ALSO update it to match what the current outlook of the project is, it has changed a little bit!

### PR DESCRIPTION
**Pull request by Jcp149**
still need to add the fixed use case diagram after talking to rohit if he likes what i did on canva!

closes #208

### CODE REVIEW

**Comment by Birdbh** [comment]
Is this dead?

**Comment by JamesShadowfyre** [comment]
@Jcp149

**Comment by Jcp149** [comment]
@JamesShadowfyre had to wait on reply from rohit, will get this done tonight

**Comment by Jcp149** [comment]
@JamesShadowfyre @Birdbh M2 is now fixed to rohits standards should be an easy accept. we should, as a group, take a look at m2 and update for M5 (without user stories)

**Review by Birdbh — APPROVED** [review]

**Review by JamesShadowfyre — APPROVED** [review]
Updates to requirements look good. Thanks!

**Pull request merged**
