### PR TITLE
Birdbh/issue145 ->  Create Prediction class that will take a sensor object and fill the prediction field based on a SARIMAX model

### PR DESCRIPTION
**Pull request by Birdbh**
This is an object that will allow for additional functionality for the sensor object to predict future values.

### CODE REVIEW

**Review by JamesShadowfyre — COMMENTED** [review]
sk learn not running properly in tests. Going to put this on hold till issue #124 is done

**Comment by JamesShadowfyre** [comment]
@Birdbh Jeffrey and I are both having issues with the SK learn module stuff. Maybe tackle #124 with the exact extensions/versions you have installed

**Comment by Birdbh** [comment]
Makes sense, on it

**Comment by Reebs296** [comment]
Have those changes that James requested been made?

**Review by JamesShadowfyre — APPROVED** [review]
Tests are passing. There are versioning issues in the test results log, but they seem to be with dependent modules and not in the project itself. 
Class seems consistent with design principles and goal

**Comment by Birdbh** [comment]
@Reebs296 Changes James Requested have been made as seen above

**Review by Reebs296 — APPROVED** [review]
I checked it over and it works mostly for me, I think there's just a file path issue on my end. If it works for James, I'll say its good then.

**Pull request merged**
