### PR TITLE
Add alarms per issue218

### PR DESCRIPTION
**Pull request by JamesShadowfyre**
This adds alarms.

### CODE REVIEW

**Comment by Birdbh** [comment]
Did some user testing with different inputs, and channels. and uploaded data. No errors but is the alarm supposed to chart a line on the sensor data chart? If so I'm not seeing it, if not works great!

image

**Review by brkykrclk — APPROVED** [review]
Looks great, thank you James

If necessary I can work on test classes to increase the test coverage

**Review by Birdbh — CHANGES_REQUESTED** [review]
Add "APScheduler" to requirments.txt, this library has been added but not updated in the requirments.txt

**Comment by JamesShadowfyre** [comment]
> Add "APScheduler" to requirments.txt, this library has been added but not updated in the requirments.txt

Where is it used? I thought I removed all references to it

**Review by Birdbh — APPROVED** [review]
I ran it after removing my npm install and it still runs, We still need one more person to check like Alex or Jefferey to be sure though. I made one commit you will have to pull for re-sizing the alarm input boxes to not overflow outside of the form div
image
Otherwise is great! thanks for taking this on. The code is a little smelly with the changes we made to home.py and routing.

**Review by Reebs296 — APPROVED** [review]
all looks good to me, appreciate that James!

**Pull request merged**
