### PR TITLE
Issue#160: Clean-up login.html file & Delete Redundant loginPage.html

### LINKED ISSUE #160: Clean-up login.html file & Delete Redundant loginPage.html

### PR DESCRIPTION
**Pull request by Reebs296**
Fixes #160

### CODE REVIEW

**Review by Jcp149 — APPROVED** [review]
looks good to me, thanks for updating the format!

**Review by Birdbh — CHANGES_REQUESTED** [review]
image
These changes to clean-up the login.html turn the jinja syntax into comments, the jinja syntax is necessary for the page to display, as can be seen in the image above, all the base.html content is gone now and the formatting from before is missing. You can see with the difference in the image below.
image

**Comment by Reebs296** [comment]
@Birdbh please see the syntax changes.

**Review by Birdbh — APPROVED** [review]
We discussed this pull request in depth during the meeting, and I am going to approve it. James may use the branch in the future for another PR.

**Pull request merged**
